# Generated by Django 4.1 on 2022-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='emp_code',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
